wamp64/www/blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Session 狀態 = 伺服器  Coolie = user
// web.php 檔案包含 RouteServiceProvider 在 web 中介層群組中放置的路由，它會提供 Session 狀態、CSRF 保護和 Cookie 加密。
// 如果你的應用程式沒有提供無狀態的 RESTful API，那麼你的所有路由可能會在 web.php 中定義。
use App\User; // 使用的資料庫
use App\Http\Resources\User as UserResource; //單筆資源
use App\Http\Resources\UserCollection; // 集合資源
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth']], function () {
    Route::get('post/loading', 'PostController@load')->name('post.loading');  // 請加在 resoure 前  post/test 最好要重新命名   重新命名 路由命名
    Route::post('post/browse', 'PostController@browse')->name('post.browse');  // 請加在 resoure 前  post/browse 最好要重新命名   重新命名 路由命名 
    Route::get('post/partial_update', 'PostController@partial_update')->name('post.partial_update');  // 導引路由到ajax測試
    Route::get('post/ajax_test', 'PostController@ajax_test')->name('post.ajax_test');  // 導引路由到ajax測試
    Route::resource('post', 'PostController'); //uri, Controller
    Route::post('message/reply','MessageController@reply')->name('message.reply');  //回復路由
    Route::resource('message', 'MessageController'); //uri, Controller
    Route::get('personal/card', 'PersonalController@card')->name('personal.card');  // 請加在 resoure 前  post/card 最好要重新命名   重新命名 路由命名
    Route::post('personal/card_img', 'PersonalController@cardimg')->name('personal.card_img');  //route,處理方式
    Route::resource('personal', 'PersonalController'); //uri, Controller
    Route::get('/user_frist', function () { //找到單筆文章 (JSON)
        return new UserResource(User::find(1));
    });
    Route::get('/user_all', function () { //找到整筆文章(JSON)
        return new UserCollection(User::all());
    });
    
    //Route::get('post')->name('post.test'); // uri, Controller 還要給路由名字 沒用到get方式 所以沒有資料 畫面是空的或錯的
    // Route::get('/showInfo',['middleware' => 'auth','uses' =>'PersonalController@showInfo']); //新增showInfo 方式
    // Route::post('/postInfo',['middleware' => 'auth','uses' =>'PersonalController@postInfo']);
    //  Route::post('message/{id}', 'PostController@addmessage')->name('post.addmessage'); //每個文章代流水號 新增方法 ->name新增路由
    //  Route::delete('message/{id}', 'PostController@deletemessage')->name('post.deletemessage'); //新增路由 刪除功能
 
});
// Route::get('post/','DoctorController@edit')->name('doctor.edit');

wamp64/www/blog/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [ //  因為posts資料表 新增欄位 (異動) 所以要增加 可以被批量賦值的，我們可以使用 create 方法來新增一筆新記錄到資料庫
        'user_id', 'title', 'content',
    ];

    public function user() //跟User model 做關聯 1個貼文屬於該創立的使用者
    {
        return $this->belongsTo('App\User');
    }
    public function addmessage() //跟User model 做關聯 1個貼文屬於該創立的使用者
    {
        return $this->hasMany('App\addmessage');
    }
    public function reply() //跟User model 做關聯 1個貼文屬於該創立的使用者
    {
        return $this->hasMany('App\Reply');
    }
    public function personal() //跟 Personal關聯
    {
        return $this->belongsTo('App\Personal');
    }
    public function visitors() //跟 visitors關聯(文章瀏覽)
   {
       return $this->hasMany('App\VisitorRegistry');
   }
}

wamp64/www/blog/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request; // 引用 HTTP請求
use Illuminate\Http\Response; // 引用 HTTP回應
use App\Http\Controllers\Controller; //控制 可有可無
use Redirect, Input, Auth, Log;  // test
use App\User; //沒有引用會錯
use App\Post; //沒有引用會錯
use App\addmessage; //沒有引用會錯
use App\Reply; //沒有引用會錯
use Validator; //引入驗證的類別
use App\VisitorRegistry; //Model
use App\Http\Requests\Post\Store; //  驗證logic 抽離 封裝成獨立的類別
use Illuminate\Contracts\Support\JsonabletoJson; //將頁面的資料 轉換為 JSON 這裡或許不需要
use Illuminate\Support\Facades\Cookie; // 通過Cookie Facade 方式 獲取Cookie
use Visitor; // 套件
//use Weboap\Visitor\Visitor as x; //變數衝突 這裡 use  Visitor::log(); 
class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public $visitor;

    //依赖注入
    public function __construct(Visitor $visitor){
        $this->visitor = $visitor;

    }
    
    public function index()
    {
        
       //$datas = Post::get(); // 把資料從Post model勞出 獲得全部資料 用for each 印出
    //    $users = auth()->user()->paginate(2);  // 傳遞給paginate方法的唯一參數是您希望“每頁”顯示的項目數
    //    dd($users);
       //dd( $posts = Post::orderBy('id', 'desc')->with('user')->paginate(10) );
    //    $datas = Post::orderBy('id', 'desc')->get() ; // 拿時間倒序
   
       $datas = Post::orderBy('id', 'desc')->with('user')->paginate(3) ; // 拿時間倒序
       
    //    $users = Post::orderBy('id', 'desc')->with('user')->paginate(1); // 拿到post(model) 相關 user(model)   並且以3個為一單位
    //    return User::paginate(1); //轉換成JSON 用來傳遞資料 可以做傳遞數量的過濾
    //    $users->withPath('personal'); // 連結分頁把路由重新導向 withPath(uri) 

    // Visitor::log(1);
       //dd($datas); //Post->id 哪篇文章

    
    // $a = cookie('cs', 'cookie',5);//新建一個Cookie對象,過期時間為5分鐘)($name,$value,$min)
    // response()->make('s')->cookie($a); //回應
    //    $x = Cookie::queue('wang', 'very good', 1); //set  cookie 柱列 後 
    //    dd(Cookie::get('wang')); //get 拿出
       return view('post.index',['datas' => $datas ]); // 渲染index.blade.php 把 後端的資料傳送到前端
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $datas = Post::get(); // 把資料從Post model勞出 獲得全部資料 用for each 印出
        return view('post.create'); // 渲染 create.blade.php 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) // HTTP請求 
    {  //把資料存入導向到其他功能最後印出資料
        
        $parameters = $request->only('title','content'); //存欄位 跟內容
        $rules =[
            'title' => 'required', //title 這個欄位是 validation required的驗證
            'content' => 'required',//content 這個欄位是 validation required的驗證
        ]; //驗證規則
        $messages =[
            'title.required' => '請輸入文章標題', // title 欄位的 validation required的驗證錯誤改寫
            'content.required' =>'請輸入文章內容',
        ]; //錯誤時改寫錯誤訊息
        $result = Validator::make( $parameters,$rules,$messages); // 先做存取 再做驗證
        if($result->fails()){ // 驗證失敗導向
            return redirect()->route('post.create')->withErrors($result); //導向 creat方法 並且帶
        }
        // request()->validate($rules, $messages); //先做驗證 在存資料  使用 Request 類別的 validate 方法
    

        // $parameters = $request->only('title','content'); //存欄位 跟內容
        $data = auth()->user()->posts()->create( $parameters); //  關聯 經過驗證的使用者 經過關聯把資料存入 posts資料表的title content欄位
        if($data){ //資料存完回主頁面
            return redirect()->route('post.index'); //重新導回 index方法
        }
      
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
    public function show($id) // 獲得的流水號  這則貼文
    {
        // dd(
        //     Post::find($id)->visitors()->get() //  拿出單筆文章 用關聯拿出資料
        // );
        // dd(
        //     Reply::where('message_id',49)->get()
        // );
        //文章ID 被 回復 ID 被吃掉了 
        // dd($id);
        $data = Post::find($id); //獲得單筆文章的資料
        if(!$data){
            return redirect()->route('post.index'); //如果資料不存在重新導向index方法
        }
        $message = addmessage::where('post_id', $id)->orderBy('created_at', 'desc')->get(); // 限制 找到文章ID 拿該筆資料全部
        // dd(Post::with('addmessage')->orderBy('created_at', 'desc')->get() ); //post 關聯 addmessage 然後倒序排序最後拿出全部
        // dd($message); // 全部留言
        if(!$message){ 
            return redirect()->route('post.show'); //如果留言不存在重新導向show方法
        }
        // $reply = Post::find($id)->addmessage()->pluck('id')->all(); //藉由ID 撈另一個ID 
        // dd($reply);
       
        // dd($message);
        // $tx = addmessage::find($reply);
        // $reply_content = Reply::where('message_id',$reply[0])->get(); //全部回復
        // dd($reply_content);
       
        // dd($$reply_content);
        Visitor::log($data->id);  //可以調用 文章瀏覽 請加入 use Visitor Model 
        $reply_content =Reply::get();
        if(!$reply_content){ 
            return redirect()->route('post.show'); //如果留言不存在重新導向show方法
        }
        //$article = Visitor::get('127.0.0.1'); //把瀏覽資料單筆全部拿出
        // $article = Visitor::all()->where('post_id', $id); //把瀏覽資料全部拿出  限制後 拿出單筆文章
        // $test =  Visitor::log($data->id);
        // dd($test);
        $visit = Post::find($id)->visitors()->get(); //  拿出單筆文章 用關聯拿出資料
      
        //dd($visit);
        //$visit = VisitorRegistry::where('post_id', $id)->get(); //把瀏覽資料全部拿出  限制後 拿出單筆文章
   
            
       // }
        return view('post.show',['data'=>$data, 'message' => $message, 'visit' => $visit,'reply_content' =>$reply_content  ]); //如果資料存在導回show.blade.php 並把data傳回前端
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) //獲得的流水號
    {
        $data = Post::find($id); //獲得單筆文章
        if(!$data){
            return redirect()->route('post.index'); //重新導向index 方法
        }
        return view('post.edit',[ 'data' => $data]); // 回前端,代參數
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $params = $request->only('title', 'content'); // 存欄位,內容
        //dd($params); // 把存的參數拿出
        $data = Post::find($id); //單筆文章
    
        if (!$data) {
            return redirect()->route('post.index');
        }
    
        $data->update($params);
        return redirect()->route('post.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) //
    {
        $data = Post::find($id);
        //dd($data); //全部留言  
        $test = addmessage::where('post_id', $id)->get()->all(); // 限制 找到文章ID 拿該筆資料全部 陣列 但是有很多陣列 所以可能要計算長度一個個刪
        //dd($test[0]->content); // 拿到第一個留言後刪除
        // count($test); //計算長度留言陣列長度 
        // dd(count($test));
        // $message = $test[0]->id;
        //dd($message); //全部留言    
        if ($data) {
            // addmessage::destroy();
            for($i=0,$message_count = count($test);$i<$message_count ;$i++){
                $message = $test[$i]->id; // 拿出每個留言的ID 
                // dd($message);
                addmessage::destroy($message); // 然後刪除留言
                Post::destroy($id); //刪除該邊文章
            }
          
            // addmessage::destroy($message);
            //$data->delete();
           
            return redirect()->route('post.index');
        }
    }

    public function load() // 等待頁面 
    {
        header("Refresh:0; url = /personal");  //php 跳轉頁面  Refresh:幾秒 uri 重新導向 相對位置 後
        //不能使用 header("Refresh:0; url = http://localhost:8000/post/browse");  //php 跳轉頁面  Refresh:幾秒 uri 重新導向 相對位置
        //header("Refresh:5; url =http://localhost:8000/personal");
        return view('post.loading'); // 渲染 loading.blade.php  先
        
    }
    public function browse(Request $request) //瀏覽文章ID
    {
       
        // header("Refresh:0; url = ./loading");  //php 跳轉頁面  Refresh:幾秒 url 重新導向 相對位置
        $rules =[
            'search' => 'required',//content 這個欄位是 validation required的驗證
        ]; //驗證規則
          $text =[
            'search.required' =>'請輸入要收尋的標題',
        ]; //錯誤時改寫錯誤訊息
        request()->validate($rules, $text); //先做驗證 在存資料  使用 Request 類別的 validate 方法
        // dd($request->input('search')); //可以是 直接取出前端所打的值
        // respone('ff')->cookie('ee','222',30);
        // $cookie = Cookie::get('search');
        // dd($cookie);
       
        // $cookie = $request->withCookie(cookie()->forever('search',3)); //把收尋的資料 存入cookie
        
        $predata = $request->flashOnly(['search']); //把前端 name="search" 先存進session
        // return redirect('post/index')->withInput($predata); //將輸入資料快閃並重導至前一頁 withInput() 帶入的參數到頁面
        $pre_search = $request->old('search'); //後端在把session 資料 撈出 加快速度
        // dd($pre_search);
        $search = $request->only('search'); //變數 存要求欄位 content 是前端的name 這裡的型態是陣列(array)
        $text = $search['search'];
      
        // sharedLock(); 共享鎖可避免選擇的資料列被更改，直到你的交易提交為止
        // dd( $text);
        // $datas = Post::get(); // 把資料從Post model勞出 獲得全部資料 用for each 印出
        $datas = Post::where('title', 'like', '%'.$text.'%')->orderBy('created_at', 'desc')->sharedLock()->get(); // 做模糊查詢 然後用時間做排序(倒敘) 把拿到的相關結果都拿出
        // dd($datas);
        // dd( count($datas) );
        //$datas_alltitle = $datas->pluck('title')->all(); // piluck後事collcetion 最後是陣列
        //dd(count($datas_alltitle)); //計算陣列長度
        //dd($search['search']); //前端送出form 的瀏覽
        for($i=0,$datas_count = count($datas);$i<$datas_count ;$i++){ //用變數i 當作撈陣列 $datas_alltitle 裡面的value
            $datas_value = $datas[$i]->title;//collcetion 之後指定 array->title 

wamp64/www/blog/resources/views/post/ajax_user.blade.php
@extends('layouts.app') 

@section('content') <!-- 個人資料 -->

<html>
<head>
      <title>Laravel Ajax示例</title>
      <meta name="_token" content="{{ csrf_token() }}"/> <!-- 可以post -->
      
   </head>
   
   <body>


 



   </body>
</html>
@endsection

wamp64/www/blog/resources/views/post/create.blade.php
@extends('layouts.app') 

@section('content')
    <div class="container">
        <form action="{{ route('post.store') }}" method="POST"> <!-- 把資料送進後端post . store 存取資料  -->
            @csrf
            <div class="form-group row">
                <label for="title" class="col-sm-1 col-form-label">標題</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" id="title" name="title" placeholder="標題">
                    
                    @if ($errors->first('title')) <!-- 當驗證沒過時  會渲染errors變數 blade 能夠從 errors 變數取出錯誤訊息，並顯示於畫面 -->
                    <span class="error" role="alert">
                        <strong>{{ $errors->first('title') }}</strong> <!-- 驗證失敗時彈出錯誤訊息  -->
                    </span>
                  @endif 
                </div>
            </div>
            <div class="form-group row">
                <label for="content" class="col-sm-1 col-form-label">內容</label>
                <div class="col-sm-4">
                    <textarea class="form-control" id="content" name="content"> 
                    </textarea> <!--收content -->

                    @if ($errors->first('content')) <!-- 當驗證沒過時  會渲染errors變數 blade 能夠從 errors 變數取出錯誤訊息，並顯示於畫面 -->
                    <span class="error" role="alert">
                        <strong>{{ $errors->first('content') }}</strong>  <!-- 驗證失敗時彈出錯誤訊息  -->
                    </span>
                     @endif
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <input type="submit" class="btn btn-primary" value="送出">
                </div>
            </div>
        </form>
    </div>
@endsection

wamp64/www/blog/resources/views/post/edit.blade.php
@extends('layouts.app') 

@section('content')
    <div class="container">
        <form action="{{ route('post.update', $data->id) }}" method="POST"> <!-- 送出更新目前內容  -->
            @csrf
            @method('PUT')
            {{-- <input type="hidden" name="_method" value="put"> --}}
            <div class="form-group row">
                <label for="title" class="col-sm-1 col-form-label">標題</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" id="title" name="title" value="{{ $data->title }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="content" class="col-sm-1 col-form-label">內容</label>
                <div class="col-sm-4">
                    <textarea class="form-control" id="content" name="content">{{ $data->content }}</textarea>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <input type="submit" class="btn btn-primary" value="送出">
                </div>
            </div>
        </form>
    </div>
@endsection

wamp64/www/blog/resources/views/post/index.blade.php
@extends('layouts.app') 

@section('content')
    <div class="container">
        <form action="{{ route('post.browse') }}" method="POST"> <!-- 收尋  -->

            @csrf
            <input type="text" class="form-control" id="search" name="search"   value="{{ old('search') }}" > <!--在把session 資料 撈出   -->  
            <button type="submit" class="btn btn-danger" >收尋</button> <!-- 繳交到後端 -->
            
              @if ($errors->first('search')) <!-- 當驗證沒過時  會渲染errors變數 blade 能夠從 errors 變數取出錯誤訊息，並顯示於畫面 -->
                    <span class="error" role="alert">
                        <strong>{{ $errors->first('search') }}</strong> <!-- 驗證失敗時彈出錯誤訊息  -->
                    </span>
                  @endif
        </form>
        
      
        <div align="center">
        <a href="{{ route('post.loading') }}" class="btn btn-primary">loading個人專區</a> <!-- 到show  -->
        <a href="{{ route('personal.index') }}" class="btn btn-primary">個人專區</a> <!-- 把資料送進personal.create -->
        <a href="{{ route('personal.card') }}" class="btn btn-primary">曬卡區專區</a> <!-- 連結personal.card -->
        <a href="{{ route('post.create') }}" class="btn btn-primary">我要貼文</a> <!-- 把資料送進post.create -->
        <a href="{{ route('post.partial_update') }}" class="btn btn-primary">部分更新測試</a> <!-- 把資料送進post.create -->
      
        </div>
        <!-- 資料存取完後 把它從資料勞出  -->
        @foreach ($datas as $key => $data)
       
            <div class="card text-center">
                <div class="card-header">
              
                    標題：{{ $data->title }}
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        作者：{{ $data->user->name }} <!-- post關聯user name  -->
                    </h5>
                    <a href="{{ route('post.show', $data->id) }}" class="btn btn-secondary">查看文章</a> <!--  經過路由導向到show功能 把主鍵送入後勞出資料 -->
                </div>
                <div class="card-footer text-muted">
                    發文日期：{{ $data->created_at }}

                </div>
            </div><br>
        @endforeach
        
        {{ $datas->links() }} <!--  生成內部剩餘鏈結  appends(['sort' => 'votes']) 附加到分頁鏈接的查詢字符串  fragment() 附加分頁鏈結的未尾 -->
    </div>
    </div>
        <!-- 資料存取完後 把它從資料勞出  -->
       
    </div>
  
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
      <script>
            // $.ajax({
            //     type: 'POST', //傳送類型
            //     url: '/post/draw', // uri
            //     data: { date : '2015-03-12'}, //測試資料
            //     dataType: 'json', //傳送的資料類型
            //     headers: { //擋頭
            //     'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content') //XSRF-TOKEN cookie 中儲存 CSRF token
            // },
            //     success: function(data){ //成功顯示
            //     console.log(data.status); //印出成功狀態
            // },
            //     error: function(xhr, type){ //錯誤彈出
            //     alert('Ajax error!')
            //     }
            // });

      </script>
    </body>

</html>

@endsection

wamp64/www/blog/resources/views/post/message.blade.php
@extends('layouts.app') 

@section('content')
    <div class="container">
        <form action="{{ route('message.update', $ed_message->id) }}" method="POST"> <!-- 送出更新目前內容  -->
            @csrf
            @method('PUT')

            <div class="form-group row">
                <label for="content" class="col-sm-1 col-form-label">內容</label>
                <div class="col-sm-4">
                    <textarea class="form-control" id="content" name="content">{{ $ed_message->content }}</textarea>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <input type="submit" class="btn btn-primary" value="送出">
                </div>
            </div>
        </form>
    </div>
@endsection

wamp64/www/blog/resources/views/post/show.blade.php
@extends('layouts.app') 

@section('content')
    <div class="container">      
        <div class="card text-center">
            <div class="card-header">
                標題：{{ $data->title }} <!-- 後端把值傳入到前端  -->
            </div>
            <div class="card-body">
                <h5 class="card-title">
                    作者：{{ $data->user->name }} <!-- post關聯user 拿出姓名  -->
                    文章ID：{{ $data->id }} <!-- post關聯user 拿出姓名  -->
                    </br>
                    @foreach ($visit as $key => $visits) <!-- 拿出單筆文章 用關聯拿出資料 -->
                    瀏覽次數：{{  $visits->clicks  }} 
                    瀏覽的IP：{{  $visits->ip  }}
                    </br>
                    @endforeach
                </h5>
                <p class="card-text">
                    {{ $data->content }}
                </p>
            </div>
            <form action="{{ route('message.store', $data->id) }}" method="POST"> <!-- 連到內部  MessageController 的 store方法 -->
                 
                    @csrf
                    <input type="hidden" name="id" value="{{ $data->id }}"> <!-- 單純抓文章ID  -->
                    <label  class="col-sm-1 col-form-label">內容</label> <!-- for=content 給後端用  -->
                <div class="col-sm-4">
                    <textarea class="form-control" id="content" name="content">   </textarea>  <!-- HTTP請求 要 儲存content欄位  -->
                    
                    @if ($errors->first('content')) <!-- 當驗證沒過時  會渲染errors變數 blade 能夠從 errors 變數取出錯誤訊息，並顯示於畫面 -->
                    <span class="error" role="alert">
                        <strong>{{ $errors->first('content') }}</strong> <!-- 驗證失敗時彈出錯誤訊息  -->
                    </span>
                  @endif
                </div>
                    <!-- <input type="hidden" name="_method" value="delete"> -->
                    <button type="submit" class="btn btn-danger" >留言</button> <!-- 繳交到後端 -->
                 
                </form>
            @foreach ($message as $key => $messages) <!-- 迭代 並且把後端送入的  $messages 改為 $message 當作從資料庫拿出的資料-->
             
             <br> <!-- post 單筆文章 對應 user model 的name屬性  -->
             留言:{{ $messages->content }} <!-- 欄位 -->
            
             
             <br>
          
             留言者名字:{{ $messages->user->name  }} <!-- 欄位 -->
             留言者email:{{ $messages->user->email }} <!-- 欄位 -->
             留言者ID:{{ $messages->user_id }} <!-- 欄位 -->
             第幾篇:{{ $messages->post_id }} <!-- 欄位 -->
             流水號:{{ $messages->id }} <!-- 欄位 -->
             創立時間:{{ $messages->created_at }} <!-- 欄位 -->
           
             <form  action="{{ route('message.destroy', $messages->id) }}" method="POST"> <!--  $messages->id 找到當前留言' -->
                @csrf

                @if(  auth()->id() === $messages->user_id)
                <a href="{{ route('message.edit', $messages->id) }}" class="btn btn-primary">編輯</a> <!--  $messages->id -- >
                @endif

                @if(  auth()->id() === $messages->user_id)  <!-- 當前使用者ID === 留言者ID -->
                @method('DELETE')
               
                <button class="btn btn-danger">刪除</button>     <!-- form表單action導向刪除動作 才能刪除 -->
                @endif
            </form>
            
                <form action="{{ route('message.reply'), $messages->id }}" method="POST"> 
                    <div>
                    @csrf
                    <input type="hidden" name="post_id" value="{{ $data->id }}"> <!-- 單純抓文章ID  -->
                    <input type="hidden" name="id" value="{{ $messages->id }}"> <!-- 單純抓留言ID  -->
                        <textarea style="width:300px  "  class="form-control" id="reply_content" name="reply_content">   </textarea>  <!-- HTTP請求 要 儲存content欄位  -->
                        @if ($errors->first('reply_content')) <!-- 當驗證沒過時  會渲染errors變數 blade 能夠從 errors 變數取出錯誤訊息，並顯示於畫面 -->
                        <span class="error" role="alert">
                            <strong>{{ $errors->first('reply_content') }}</strong> <!-- 驗證失敗時彈出錯誤訊息  -->
                        </span>
                         @endif
                         
                        
                         @foreach ($reply_content as $key => $reply_contents)
                         @if(  $reply_contents->message_id === $messages->id)
                           回復:{{ $reply_contents->content }}</br>
                           @endif
                         @endforeach
                        
                        <button type="submit" class="btn btn-danger" >留言</button> <!-- 繳交到後端 -->
                       
                    </div>
                </form>
          
           
         
         @endforeach
       
            <div class="card-footer text-muted">
                發文日期：{{ $data->created_at }}
            </div>
            
            <div align="center">

         

                <form action="{{ route('post.destroy', $data->id) }}" method="POST"> <!-- 單筆文章的動作 -->
                    @csrf
                    @if(  auth()->id() === $data->user_id)  <!-- 當前使用者ID === 貼文者ID -->
                     <a href="{{ route('post.edit', $data->id) }}" class="btn btn-primary">編輯</a>
                   
                    @method('DELETE') <!--  HTTP刪除 -->
                    {{-- <input type="hidden" name="_method" value="delete"> --}}
                    <button class="btn btn-danger">刪除</button>
                     @endif
                </form>
               

            </div>
        </div>
    </div>
@endsection